### PR TITLE
Add package link for archlinux

### PR DESCRIPTION
**Pull request by oktomus**
[https://aur.archlinux.org/packages/tev/](https://aur.archlinux.org/packages/tev/)

### CODE REVIEW

**Comment by Tom94** [comment]
Hi oktomus,

thanks for putting tev on the AUR. However, I am concerned that some dependencies might be missing from the PKGBUILD, namely X, OpenGL, and zlib. Are these perhaps implicitly handled somehow? Unfortunately I do not have a clean Arch install lying around to check that the installation works out-of-the-box.

Cheers,
Tom94

**Comment by oktomus** [comment]
Hey @Tom94, yes they are :) 
I tested on my installation but I will test it on a clean installation soon. 
- zlib is in the core
- X is installed as soon as you have a graphic environment
Except opengl, that I will add now !

**Comment by oktomus** [comment]
Tested on a clean installation, building failling because it hasn't rights to copy in /usr. I will try to fix it, still new with package building :)

**Comment by oktomus** [comment]
Package fixed, builds and installs like a charm :)

**Comment by Tom94** [comment]
Perfect, this looks a lot better. Thank you very much! :)

**Pull request merged**
